# Generated by Django 4.1.7 on 2023-04-25 16:43

from django.db import migrations, models
import services.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_user_date_of_birth_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_picture",
            field=models.ImageField(
                null=True,
                storage=services.storage_backends.public_storage,
                upload_to="",
            ),
        ),
    ]
